easybites/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('recipes/', include('recipes.urls')),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home')
]

recipes/urls.py
from django.urls import path
from .views import RecipeAdd
from . import views


urlpatterns = [
    path('', views.RecipeList.as_view(), name='recipes'),
    path('<slug:slug>/', views.RecipeDetail.as_view(), name='recipes_detail'),
    path('like/<slug:slug>', views.RecipeLike.as_view(), name='recipes_like'),
    path('add_recipe/', views.RecipeAdd.as_view(), name='recipe_add'),
]

recipes/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse

STATUS = ((0, "Draft"), (1, "Published"))

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipe_post')
    date_updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField(max_length=500, null=True)
    featured_image = CloudinaryField('image', default='placeholder')
    overview = models.TextField(blank=True)
    date_created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name="recipe_likes", blank=True)

    class Meta:
        ordering = ['-date_created_on']

    def __str__(self):
        return str(self.title)

    def number_of_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('recipe')

class Comment(models.Model):
    post = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    date_created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['date_created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

recipes/forms.py
from .models import Comment, Recipe
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'author', 'description', 'featured_image',)

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, '../templates/index.html')

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Recipe
from .forms import CommentForm, RecipeForm


class RecipeList(generic.ListView):
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by("-date_created_on")
    template_name = 'recipes.html'
    paginate_by = 6

class RecipeDetail(View):

     def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by("-date_created_on")
        liked = False
        if recipe.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "recipes_detail.html",
            {
                "recipe": recipe,
                "comments": comments,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

        def post(self, request, slug, *args, **kwargs):

            queryset = Recipe.objects.filter(status=1)
            recipe = get_object_or_404(queryset, slug=slug)
            comments = post.comments.filter(approved=True).order_by("-date_created_on")
            liked = False
            if post.likes.filter(id=self.request.user.id).exists():
                liked = True

            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                comment_form.instance.email = request.user.email
                comment_form.instance.name = request.user.username
                comment = comment_form.save(commit=False)
                comment.recipe = recipe
                comment.save()
            else:
                comment_form = CommentForm()

            return render(
                request,
                "recipes_detail.html",
                {
                    "recipe": recipe,
                    "comments": comments,
                    "commented": True,
                    "comment_form": comment_form,
                    "liked": liked
                },
            )

    

class RecipeLike(View):
    def post(self, request, slug, *args, **kwargs):
        recipe = get_object_or_404(Recipe, slug=slug)
        if recipe.likes.filter(id=request.user.id).exists():
            recipe.likes.remove(request.user)
        else:
            recipe.likes.add(request.user)

        return HttpResponseRedirect(reverse('recipes_detail', args=[slug]))


class RecipeAdd(LoginRequiredMixin, CreateView):
        model = Recipe
        form_class = RecipeForm
        template_name = 'add_recipe.html'

        def form_valid(self, form):

            form.instance.author = self.request.user
            return super(CreateView, self).form_valid(form)

home/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="home">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <h1>hello</h1>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/add_recipe.html
{% extends "base.html" %} 
{% load static %}
{% block content %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                {% if recipe %}
                <h1 class="title mt-70">Add Recipe {{ user.username }}</h1>
                {% else %}
                <h1 class="title mt-70">Edit Recipe {{ user.username }}</h1>
                {% endif %}
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="w-50 table">
                    {% for field in form %}
                    <tr>
                        <th>{{field.label}}</th>
                        <td>{{ field }}</td>
                    </tr>
                    {% endfor %}
                </table>
                <div class="text-center">
                    <button class="btn btn-secondary right mb-4" type="submit" value="Save">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>Easy Bites</title>
  </head>
  <body>
   <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="col-4">
          <a class="navbar-brand" href="{% url 'home' %}">Easy Bites</a> 
        </div>
        <div class="col-4">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'recipes' %}">Recipes</a>
              </li>

              {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}

            </ul>
          </div>
        </div>
      </div>
    </nav>
   </header>
    <main>
      {% block content %}

      {% endblock %}
    </main>
    <footer class="fixed-bottom mt-auto py-4">
      <div>
          <ul class="social-networks">
              <li>
                  <a href="https://www.youtube.com/" target="_blank" rel="noopener"
                      aria-label="Visit our Youtube channel (opens in a new tab)"><i
                          class="fa-brands fa-youtube"></i></a>
              </li>
              <li>
                  <a href="https://www.instagram.com/" target="_blank" rel="noopener"
                      aria-label="Visit our Instagram page (opens in a new tab)"><i
                          class="fa-brands fa-instagram"></i></a>
              </li>
              <li>
                  <a href="https://www.facebook.com/" target="_blank" rel="noopener"
                      aria-label="Visit our Facebook page (opens in a new tab)"><i
                          class="fa-brands fa-facebook-f"></i></a>
              </li>
              <li>
                  <a href="https://www.twitter.com/" target="_blank" rel="noopener"
                      aria-label="Visit our Twitter page (opens in a new tab)"><i
                          class="fa-brands fa-square-twitter"></i></a>
              </li>
          </ul>
      </div>
  </footer>
    <script src="https://kit.fontawesome.com/ba9ae38aaf.js" crossorigin="anonymous"></script>
  </body>
</html>

templates/recipes.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="home">
    <div class="container">

        <!--Recipe Posts-->
        <div class="col-12 mt-3">
            <div class="row">
                {% for recipe in recipe_list %}
                <div class="card" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                     <a href="{% url 'recipes_detail' recipe.slug %}" class="recipe-link">
                      <h5 class="card-title">{{ recipe.title }}</h5>
                      <p class="card-overview">{{ recipe.overview }}</p>
                      </a>
                      <p class="author">Author: {{ recipe.author }}</p>
                      <p class="card-text text-muted h6">{{ recipe.date_created_on}} <i class="far fa-heart"></i>
                        {{ recipe.number_of_likes }}</p>
                    </div>   
                    {% if forloop.counter|divisibleby:3 %}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        
        {% if user.is_authenticated %}
        <div class="text-center">
            <a href="{% url 'recipe_add' %}" class="btn btn-signup btn-lg mb-4">Add Recipe</a>
        </div>
    {% endif %}


        {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
    </div>
</section>
{% endblock %}

templates/recipes_detail.html
{% extends "base.html" %} 
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<!--Recipe image & title-->
<section>
<div class="container">
    <div class="row">
            <div class="col-md-6">
                <img class="recipe-image" src="{{ recipe.featured_image.url }}">
            </div>
            <div class="recipe-description">
                <h1 class="recipe-title">{{ recipe.title }}</h1>
            </div>
    </div>


<!--Recipe description-->
    <div class="row">
        <div class="col card mb-4">
            <div class="card-body">
                <p class="card-text ">
                    {{ recipe.description }}
                </p>        
    </div>
        </div>
            </div>

<!--Edit recipe-->
            {% if user.is_authenticated %}
                    <div class="text-center">
                        <a href="edit_recipe" class="btn-edit btn-sm btn-secondary mb-3">Edit</a>
                    </div>
                    {% endif %}

<!--Recipe likes & number of comments-->
                <div class="row">
                    <div class="col-1">
                        {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'recipes_like' recipe.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="recipepost_id" value="{{recipe.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="recipepost_id" value="{{recipe.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <span class="text-secondary">{{ recipe.number_of_likes }} </span>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <p class="text-secondary"><i class="far fa-comments"></i>
                            {{ total_comments }}</p>
                        {% endwith %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 card mb-4  mt-3 ">
                        <h3>Comments:</h3>
                        <div class="card-body">
                            {% for comment in comments %}
                            <div class="comments">
                                <p class="font-weight-bold">
                                    {{ comment.name }}
                                    <span class=" text-muted font-weight-normal">
                                        {{ comment.date_created_on }}
                                    </span> wrote:
                                </p>
                                {{ comment.body | linebreaks }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                <div class="col-md-4 card mb-4  mt-3 ">
                    <div class="card-body">
                        {% if commented %}
                        <div class="alert alert-success" role="alert">
                            Your comment is awaiting approval
                        </div>
                        {% else %}
                        {% if user.is_authenticated %}
        
                        <h3>Leave a comment:</h3>
                        <p>Posting as: {{ user.username }}</p>
                        <form method="post" style="margin-top: 1.3em;">
                            {{ comment_form | crispy }}
                            {% csrf_token %}
                            <button type="submit" class="btn btn-signup btn-lg mt-5">Submit</button>
                        </form>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
</section>
{% endblock content %}